/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.rajat.cafenewproject;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ASUS
 */
public class CoffeeSales extends javax.swing.JPanel {
Singleton conn = Singleton.Display();
    /**
     * Creates new form CoffeeSales
     */
    public CoffeeSales() {
        initComponents();
        setLayout(new BorderLayout());

    JLabel title = new JLabel("Total Sales Per Customer", JLabel.CENTER);
    title.setFont(new Font("Arial", Font.BOLD, 20));
    add(title, BorderLayout.NORTH);

    DefaultCategoryDataset dataset = getSalesDataset();

    JFreeChart chart = ChartFactory.createBarChart(
            "Customer Sales", "Customer", "Total Amount",
            dataset, PlotOrientation.VERTICAL,
            false, true, false);

    // Plot aur renderer nikaal
    CategoryPlot plot = chart.getCategoryPlot();
    BarRenderer renderer = new BarRenderer();

    // Color fix kar
    renderer.setSeriesPaint(0, new Color(255, 99, 71)); // tomato red

    // Gradient hata
    renderer.setBarPainter(new StandardBarPainter()); // no gradient
    plot.setRenderer(renderer);

    ChartPanel chartPanel = new ChartPanel(chart);
    add(chartPanel, BorderLayout.CENTER);
    }
    
     private DefaultCategoryDataset getSalesDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        String orderQuery = "SELECT id, customerName FROM orderedtable";    //

        try {
            PreparedStatement ps1 = conn.conn.prepareStatement(orderQuery);
             ResultSet rs1 = ps1.executeQuery();

            while (rs1.next()) {
                int orderId = rs1.getInt("id");
                String customerName = rs1.getString("customerName");

                double totalSales = 0;

                String detailQuery = "SELECT quantity, price FROM orderDetailsTable WHERE orderId = ?";
                try (PreparedStatement ps2 = conn.conn.prepareStatement(detailQuery)) {
                    ps2.setInt(1, orderId);
                    ResultSet result = ps2.executeQuery();

                    while (result.next()) {
                        int qty = result.getInt("quantity");
                        double price = result.getDouble("price");
                        totalSales += qty * price;
                    }
                }

                // Add to chart dataset
                dataset.setValue(totalSales, "Sales", customerName);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return dataset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
