/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.rajat.cafenewproject;

import javax.swing.JOptionPane;
import com.rajat.cafenewproject.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author i_rajat_1
 */
public class Customer extends javax.swing.JPanel {

Singleton con = Singleton.Display();
ArrayList<CustomerModel> custmerlist = new ArrayList<>();
    
    int selectedId = 0;

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        getTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void getTable(){
        try{
            String CustomerHeader[] = {"id","name","email","contact","address"};
            DefaultTableModel Model = new DefaultTableModel(null,CustomerHeader);
            CustomerTable.setModel(Model);
            Model.setRowCount(0);
            
            String getQuerry = "SELECT * FROM customerTable";
            Statement obj = con.conn.createStatement();
            ResultSet resultobj1 = obj.executeQuery(getQuerry);
             custmerlist.clear();
             
             while(resultobj1.next()){
             custmerlist.add(new CustomerModel(
                     resultobj1.getInt("id"),
                     resultobj1.getString("name"),
                     resultobj1.getString("email"),
                     resultobj1.getString("contact"),
                     resultobj1.getString("address")
             ));
////             
             }
             
             Object[] row = new Object[5];
             
             for(CustomerModel itemCustomerVar : custmerlist){
                 row[0] = itemCustomerVar.getid();
                 row[1] = itemCustomerVar.getname();
                 row[2] = itemCustomerVar.getemail();     
                 row[3] = itemCustomerVar.getcontact();
                 row[4] = itemCustomerVar.getaddress();
                 Model.addRow(row);
             }   
             
        }catch(SQLException exception){
           System.out.println("Check Excepiton: "+exception);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerDashPanel = new javax.swing.JPanel();
        CustomerLabel = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        CustomerEmailLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        ContactLabel = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        CustomerAddressLabel = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        Addbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        Deletebtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(630, 520));
        setPreferredSize(new java.awt.Dimension(630, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerDashPanel.setBackground(new java.awt.Color(0, 140, 140));
        CustomerDashPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CustomerLabel.setForeground(new java.awt.Color(255, 236, 209));
        CustomerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerLabel.setText("Customer Detail");
        CustomerDashPanel.add(CustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 630, -1));

        add(CustomerDashPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        CustomerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerNameLabel.setText("Full Name");
        add(CustomerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 20));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, -1));

        CustomerEmailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerEmailLabel.setText("   Email");
        CustomerEmailLabel.setMaximumSize(new java.awt.Dimension(54, 16));
        CustomerEmailLabel.setMinimumSize(new java.awt.Dimension(54, 16));
        CustomerEmailLabel.setPreferredSize(new java.awt.Dimension(54, 16));
        add(CustomerEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 90, 20));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 120, -1));

        ContactLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ContactLabel.setText("Contact No.");
        add(ContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 20));

        contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contact.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, -1));

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 120, -1));

        CustomerAddressLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerAddressLabel.setText("   Address");
        CustomerAddressLabel.setMaximumSize(new java.awt.Dimension(54, 16));
        CustomerAddressLabel.setMinimumSize(new java.awt.Dimension(54, 16));
        CustomerAddressLabel.setPreferredSize(new java.awt.Dimension(54, 16));
        add(CustomerAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 90, 20));

        BackBtn.setBackground(new java.awt.Color(0, 140, 140));
        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 236, 209));
        BackBtn.setText("BACK");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 180, -1));

        Addbtn.setBackground(new java.awt.Color(0, 140, 140));
        Addbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addbtn.setForeground(new java.awt.Color(255, 236, 209));
        Addbtn.setText("ADD ");
        Addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddbtnMouseClicked(evt);
            }
        });
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 180, -1));

        CustomerTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Email", "Contact", "Address"
            }
        ));
        CustomerTable.setToolTipText("");
        jScrollPane1.setViewportView(CustomerTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 610, 240));

        Deletebtn.setBackground(new java.awt.Color(0, 140, 140));
        Deletebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deletebtn.setForeground(new java.awt.Color(255, 236, 209));
        Deletebtn.setText("DELETE");
        Deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletebtnMouseClicked(evt);
            }
        });
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 180, -1));

        Updatebtn.setBackground(new java.awt.Color(0, 140, 140));
        Updatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Updatebtn.setForeground(new java.awt.Color(255, 236, 209));
        Updatebtn.setText("UPDATE");
        add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
       if(name.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Enter your Name !");
                }   else if(email.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Enter your Email !");
                }  else if(email.getText().endsWith("@gmail.com")){
                    JOptionPane.showMessageDialog(this, "Gmail end with @gmail.com");
                }else if(contact.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Enter your Phone Number !");
                }  else if(contact.getText().length() < 10){
                    JOptionPane.showMessageDialog(this, "Your Number is less-than 10-digits \n Please entery 10-digits Number !");
                }else if(contact.getText().length() > 10){
                    JOptionPane.showMessageDialog(this, "Your Number is Greater-than 10-digits \n Please entery 10-digits Number !");
                }else if(address.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Enter your Address !");
                }   else    {
                    try {
                    String isntVar = "INSERT INTO customerTable(name,email,contact,address) values(?,?,?,?)";
                    PreparedStatement ps = con.conn.prepareCall(isntVar);
                    ps.setString(1,name.getText());
                    ps.setString(2,email.getText());
                    ps.setString(3,contact.getText());
                    ps.setString(4,address.getText());
                 //   ps.setString(5,PhoneTEXT.getText());
                 
                 if(ps.executeUpdate() >  0){
                     JOptionPane.showMessageDialog(this, "Data Inserted !");
                     
                 }
                     }catch(SQLException e){
                         System.out.println("Check Exception: "+e);
                     }
                }
//                            System.out.println(e);                    }
    }//GEN-LAST:event_AddbtnActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // TODO add your handling code here:
        DashboardNew dash = new DashboardNew();
        dash.setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
//        if (selectedId <= 0) {
//        JOptionPane.showMessageDialog(this, "No record selected to delete.");
//        return;
//    }
//
//    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
//
//    if (confirm == JOptionPane.YES_OPTION) {
//        String deleteQuery = "DELETE FROM customertable WHERE id=?";
//        try {
//            PreparedStatement ps = con.conn.prepareStatement(deleteQuery);
//            ps.setInt(1, selectedId);
//            int deleted = ps.executeUpdate();
//
//            if (deleted > 0) {
//                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
//                selectedId = 0;
//                getTable();
//            } else {
//                JOptionPane.showMessageDialog(this, "Failed to delete record.");
//            }
//        } catch (SQLException e) {
//            System.out.println("Delete error: " + e);
//        }
//    }
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void AddbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbtnMouseClicked
        // TODO add your handling code here:
//        if(Addbtn.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Enter your Name !");
//                }  else if (CoffeeQuantity.getText().isEmpty()){
//                    JOptionPane.showMessageDialog(this, "Enter Coffee Quantity !");
//                } else {
//                       try {
//                           
//    String isntVar = " INSERT INTO MenuTable(Coffee,CoffeeType,CoffeeQuantity,Category) values(?,?,?,?)";
//                                   PreparedStatement ps = con.conn.prepareCall(isntVar);
//                                   ps.setString(1,Coffee.getSelectedItem().toString());
//                                   ps.setString(2,CoffeeType.getSelectedItem().toString());
//                                   ps.setString(3,CoffeeQuantity.getText());                                 
//                                   ps.setString(4,Category.getSelectedItem().toString());
//                                   
//                                   if(ps.executeUpdate() >  0){
//                     JOptionPane.showMessageDialog(this, "Data Inserted !");                    
//                 }
//                     }catch(SQLException e){
//                         System.out.println("Check Exception: "+e);
//                     }
//                }     
    }//GEN-LAST:event_AddbtnMouseClicked

    private void DeletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebtnMouseClicked
        // TODO add your handling code here:
        if (selectedId <= 0) {
        JOptionPane.showMessageDialog(this, "No record selected to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        String deleteQuery = "DELETE FROM customertable WHERE id=?";
        try {
            PreparedStatement ps = con.conn.prepareStatement(deleteQuery);
            ps.setInt(1, selectedId);
            int deleted = ps.executeUpdate();

            if (deleted > 0) {
                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
                selectedId = 0;
                getTable();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete record.");
            }
        } catch (SQLException e) {
            System.out.println("Delete error: " + e);
        }
    }
    }//GEN-LAST:event_DeletebtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JLabel CustomerAddressLabel;
    private javax.swing.JPanel CustomerDashPanel;
    private javax.swing.JLabel CustomerEmailLabel;
    private javax.swing.JLabel CustomerLabel;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JTextField address;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
