/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rajat.cafenewproject;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author i_rajat_1
 */
public class DashboardNew extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardNew.class.getName());

    /**
     * Creates new form DashboardNew
     */
    public DashboardNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FullPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HomePanel = new javax.swing.JPanel();
        textHome = new javax.swing.JLabel();
        MenuitemPanel = new javax.swing.JPanel();
        MenuLabel = new javax.swing.JLabel();
        MenuitemPanel1 = new javax.swing.JPanel();
        MenuLabel1 = new javax.swing.JLabel();
        CustomerPanel = new javax.swing.JPanel();
        CustomerLabel = new javax.swing.JLabel();
        StaffMangerPanel = new javax.swing.JPanel();
        StaffLabel = new javax.swing.JLabel();
        OrederedPanel = new javax.swing.JPanel();
        OrederedLabel = new javax.swing.JLabel();
        SalesReportPanel = new javax.swing.JPanel();
        SalesReportLabel = new javax.swing.JLabel();
        orderViewPanel = new javax.swing.JPanel();
        OrderViewLabel = new javax.swing.JLabel();
        dash = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CommonL = new javax.swing.JLabel();
        Common = new javax.swing.JComboBox<>();
        HotL = new javax.swing.JLabel();
        Hot = new javax.swing.JComboBox<>();
        ColdL = new javax.swing.JLabel();
        COLD = new javax.swing.JComboBox<>();
        IcedL = new javax.swing.JLabel();
        Iced = new javax.swing.JComboBox<>();
        Logoutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FullPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 110, 110));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 236, 209));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COFFEE   SHOP   AUTOMATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, -1));

        HomePanel.setBackground(new java.awt.Color(0, 110, 110));
        HomePanel.setForeground(new java.awt.Color(255, 255, 255));
        HomePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomePanelMouseExited(evt);
            }
        });
        HomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textHome.setForeground(new java.awt.Color(255, 236, 209));
        textHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textHome.setText("Home");
        textHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textHomeMouseClicked(evt);
            }
        });
        HomePanel.add(textHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, -1));

        MenuitemPanel.setBackground(new java.awt.Color(102, 0, 0));
        MenuitemPanel.setForeground(new java.awt.Color(62, 0, 12));
        MenuitemPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuitemPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuitemPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuitemPanelMouseExited(evt);
            }
        });
        MenuitemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuLabel.setForeground(new java.awt.Color(255, 236, 209));
        MenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuLabel.setText("Menu Item");
        MenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuLabelMouseExited(evt);
            }
        });
        MenuitemPanel.add(MenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 17, 130, -1));

        HomePanel.add(MenuitemPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 120, 50));

        jPanel2.add(HomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 80, 50));

        MenuitemPanel1.setBackground(new java.awt.Color(0, 110, 110));
        MenuitemPanel1.setForeground(new java.awt.Color(255, 255, 255));
        MenuitemPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuitemPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuitemPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuitemPanel1MouseExited(evt);
            }
        });
        MenuitemPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuLabel1.setForeground(new java.awt.Color(255, 236, 209));
        MenuLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuLabel1.setText("Menu Item");
        MenuLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuLabel1MouseExited(evt);
            }
        });
        MenuitemPanel1.add(MenuLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 20));

        jPanel2.add(MenuitemPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 100, 50));

        CustomerPanel.setBackground(new java.awt.Color(0, 110, 110));
        CustomerPanel.setForeground(new java.awt.Color(255, 255, 255));
        CustomerPanel.setPreferredSize(new java.awt.Dimension(130, 50));
        CustomerPanel.setRequestFocusEnabled(false);
        CustomerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CustomerPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CustomerPanelMouseExited(evt);
            }
        });
        CustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerLabel.setForeground(new java.awt.Color(255, 236, 209));
        CustomerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerLabel.setText("Customer");
        CustomerLabel.setPreferredSize(new java.awt.Dimension(76, 17));
        CustomerPanel.add(CustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 20));

        jPanel2.add(CustomerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 100, 50));

        StaffMangerPanel.setBackground(new java.awt.Color(0, 110, 110));
        StaffMangerPanel.setForeground(new java.awt.Color(255, 255, 255));
        StaffMangerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffMangerPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StaffMangerPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StaffMangerPanelMouseExited(evt);
            }
        });
        StaffMangerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StaffLabel.setForeground(new java.awt.Color(255, 236, 209));
        StaffLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StaffLabel.setText("Staff");
        StaffLabel.setMaximumSize(new java.awt.Dimension(76, 17));
        StaffLabel.setMinimumSize(new java.awt.Dimension(76, 17));
        StaffLabel.setPreferredSize(new java.awt.Dimension(76, 17));
        StaffMangerPanel.add(StaffLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, -1));

        jPanel2.add(StaffMangerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 80, 50));

        OrederedPanel.setBackground(new java.awt.Color(0, 110, 110));
        OrederedPanel.setForeground(new java.awt.Color(255, 255, 255));
        OrederedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrederedPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrederedPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrederedPanelMouseExited(evt);
            }
        });
        OrederedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrederedLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OrederedLabel.setForeground(new java.awt.Color(255, 236, 209));
        OrederedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrederedLabel.setText("Order");
        OrederedPanel.add(OrederedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        jPanel2.add(OrederedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, 50));

        SalesReportPanel.setBackground(new java.awt.Color(0, 110, 110));
        SalesReportPanel.setForeground(new java.awt.Color(255, 255, 255));
        SalesReportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesReportPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalesReportPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalesReportPanelMouseExited(evt);
            }
        });
        SalesReportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalesReportLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SalesReportLabel.setForeground(new java.awt.Color(255, 236, 209));
        SalesReportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalesReportLabel.setText("Sales");
        SalesReportPanel.add(SalesReportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 20));

        jPanel2.add(SalesReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 80, 50));

        orderViewPanel.setBackground(new java.awt.Color(0, 110, 110));
        orderViewPanel.setForeground(new java.awt.Color(255, 255, 255));
        orderViewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderViewPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderViewPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderViewPanelMouseExited(evt);
            }
        });

        OrderViewLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OrderViewLabel.setForeground(new java.awt.Color(255, 236, 209));
        OrderViewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderViewLabel.setText("Order View");
        OrderViewLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrderViewLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout orderViewPanelLayout = new javax.swing.GroupLayout(orderViewPanel);
        orderViewPanel.setLayout(orderViewPanelLayout);
        orderViewPanelLayout.setHorizontalGroup(
            orderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderViewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        orderViewPanelLayout.setVerticalGroup(
            orderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderViewPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(OrderViewLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(orderViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 100, 50));

        FullPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 88));

        dash.setMinimumSize(new java.awt.Dimension(630, 490));
        dash.setPreferredSize(new java.awt.Dimension(630, 490));
        dash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\i_rajat_1\\Pictures\\DownloadPics\\Desktop.jpg")); // NOI18N
        dash.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 340));

        CommonL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CommonL.setText("Popular Coffee");
        dash.add(CommonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 120, 20));

        Common.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Common.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espresso", "Cappuccino", "Latte", "Americano" }));
        dash.add(Common, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 120, -1));

        HotL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HotL.setText("Hot Coffee");
        dash.add(HotL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 120, -1));

        Hot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cappuccino", "Latte", "Macchiato", "Americano", "Irish Cofee" }));
        dash.add(Hot, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 120, -1));

        ColdL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ColdL.setText("Cold Coffee");
        dash.add(ColdL, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 110, -1));

        COLD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        COLD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cold Brew", "Frapped", "Cafe Glace", "Affogato" }));
        COLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLDActionPerformed(evt);
            }
        });
        dash.add(COLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 110, -1));

        IcedL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IcedL.setText("Iced Coffee");
        dash.add(IcedL, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 120, -1));

        Iced.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Iced.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Americano", "Latte", "Cappuccino", "Mocha", "Flate White" }));
        dash.add(Iced, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 120, -1));

        Logoutbtn.setBackground(new java.awt.Color(0, 110, 110));
        Logoutbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Logoutbtn.setForeground(new java.awt.Color(255, 236, 209));
        Logoutbtn.setText("LOGOUT");
        Logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutbtnMouseClicked(evt);
            }
        });
        dash.add(Logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 610, 30));

        FullPanel.add(dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 630, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FullPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FullPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMouseEntered
        // TODO add your handling code here:
        HomePanel.setBackground(new Color(0,120,120));
        textHome.setForeground(Color.white);
    }//GEN-LAST:event_HomePanelMouseEntered

    private void HomePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMouseExited
        // TODO add your handling code here:
        HomePanel.setBackground(new Color(0,140,140));
        textHome.setForeground(new Color(255,236,209));
    }//GEN-LAST:event_HomePanelMouseExited

    private void MenuLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLabelMouseEntered
        // TODO add your handling code here:
        //            MenuitemPanel.setBackground(Color.black);
        //            MenuLabel.setForeground(Color.white);
    }//GEN-LAST:event_MenuLabelMouseEntered

    private void MenuLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLabelMouseExited
        // TODO add your handling code here:
        //        MenuitemPanel.setBackground(Color.white);
        //        MenuLabel.setForeground(Color.black);
    }//GEN-LAST:event_MenuLabelMouseExited

    private void MenuitemPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuitemPanelMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_MenuitemPanelMouseClicked

    private void MenuitemPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuitemPanelMouseEntered
        // TODO add your handling code here:
//        MenuitemPanel.setBackground(Color.gray);
//        MenuitemPanel.setForeground(Color.white);
    }//GEN-LAST:event_MenuitemPanelMouseEntered

    private void MenuitemPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuitemPanelMouseExited
        // TODO add your handling code here:
//        MenuitemPanel.setBackground(new Color(62,0,12));
//        MenuitemPanel.setForeground(new Color(255,236,209));
    }//GEN-LAST:event_MenuitemPanelMouseExited

    private void HomePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMouseClicked
        // TODO add your handling code here:
                DashboardNew home = new DashboardNew();
                    home.setVisible(true);
       
    }//GEN-LAST:event_HomePanelMouseClicked

    private void MenuLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLabel1MouseEntered
        // TODO add your handling code here:
        //            MenuitemPanel.setBackground(Color.black);
        //            MenuLabel.setForeground(Color.white);
    }//GEN-LAST:event_MenuLabel1MouseEntered

    private void MenuLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLabel1MouseExited
        // TODO add your handling code here:
        //        MenuitemPanel.setBackground(Color.white);
        //        MenuLabel.setForeground(Color.black);
    }//GEN-LAST:event_MenuLabel1MouseExited

    private void MenuitemPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuitemPanel1MouseClicked
        // TODO add your handling code here:
                Menuitem menu = new Menuitem();
                dash.setLayout(new BorderLayout());
                dash.removeAll();
                dash.add(menu, BorderLayout.CENTER);
                dash.revalidate();
                dash.repaint();
    }//GEN-LAST:event_MenuitemPanel1MouseClicked

    private void MenuitemPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuitemPanel1MouseEntered
        // TODO add your handling code here:
        MenuitemPanel1.setBackground(new Color(0,120,120));
        MenuitemPanel1.setForeground(Color.white);
    }//GEN-LAST:event_MenuitemPanel1MouseEntered

    private void MenuitemPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuitemPanel1MouseExited
        // TODO add your handling code here:
        MenuitemPanel1.setBackground(new Color(0,140,140));
        MenuitemPanel1.setForeground(new Color(255,236,209));
    }//GEN-LAST:event_MenuitemPanel1MouseExited

    private void CustomerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelMouseClicked
        // TODO add your handling code here:
                Customer customer = new Customer();
                dash.setLayout(new BorderLayout());
                dash.removeAll();
                dash.add(customer, BorderLayout.CENTER);
                dash.revalidate();
                dash.repaint();
    }//GEN-LAST:event_CustomerPanelMouseClicked

    private void CustomerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelMouseEntered
        // TODO add your handling code here:
        CustomerPanel.setBackground(new Color(0,120,120));
        CustomerPanel.setForeground(Color.white);
    }//GEN-LAST:event_CustomerPanelMouseEntered

    private void CustomerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelMouseExited
        // TODO add your handling code here:
        CustomerPanel.setBackground(new Color(0,140,140));
        CustomerPanel.setForeground(new Color(255,236,209));
    }//GEN-LAST:event_CustomerPanelMouseExited

    private void StaffMangerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffMangerPanelMouseClicked
        // TODO add your handling code here:
                Staff staff = new Staff();
                dash.setLayout(new BorderLayout());
                dash.removeAll();
                dash.add(staff, BorderLayout.CENTER);
                dash.revalidate();
                dash.repaint();
    }//GEN-LAST:event_StaffMangerPanelMouseClicked

    private void StaffMangerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffMangerPanelMouseEntered
        // TODO add your handling code here:
        StaffMangerPanel.setBackground(new Color(0,120,120));
        StaffMangerPanel.setForeground(Color.white);
    }//GEN-LAST:event_StaffMangerPanelMouseEntered

    private void StaffMangerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffMangerPanelMouseExited
        // TODO add your handling code here:
        StaffMangerPanel.setBackground(new Color(0,140,140));
        StaffMangerPanel.setForeground(new Color(255,236,209));
    }//GEN-LAST:event_StaffMangerPanelMouseExited

    private void OrederedPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrederedPanelMouseClicked
        // TODO add your handling code here:
                Ordered ordered = new Ordered();
                dash.setLayout(new BorderLayout());
                dash.removeAll();
                dash.add(ordered, BorderLayout.CENTER);
                dash.revalidate();
                dash.repaint();
    }//GEN-LAST:event_OrederedPanelMouseClicked

    private void OrederedPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrederedPanelMouseEntered
        // TODO add your handling code here:
        OrederedPanel.setBackground(new Color(0,120,120));
        OrederedPanel.setForeground(Color.white);
    }//GEN-LAST:event_OrederedPanelMouseEntered

    private void OrederedPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrederedPanelMouseExited
        // TODO add your handling code here:
        OrederedPanel.setBackground(new Color(0,140,140));
        OrederedPanel.setForeground(new Color(255,236,209));
    }//GEN-LAST:event_OrederedPanelMouseExited

    private void SalesReportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesReportPanelMouseClicked
        // TODO add your handling code here:
                CoffeeSales sales = new CoffeeSales();
                dash.setLayout(new BorderLayout());
                dash.removeAll();
                dash.add(sales, BorderLayout.CENTER);
                dash.revalidate();
                dash.repaint();
    }//GEN-LAST:event_SalesReportPanelMouseClicked

    private void SalesReportPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesReportPanelMouseEntered
        // TODO add your handling code here:
        SalesReportPanel.setBackground(new Color(0,120,120));
        SalesReportPanel.setForeground(Color.white);
    }//GEN-LAST:event_SalesReportPanelMouseEntered

    private void SalesReportPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesReportPanelMouseExited
        // TODO add your handling code here:
        SalesReportPanel.setBackground(new Color(0,140,140));
        SalesReportPanel.setForeground(new Color(255,236,209));
    }//GEN-LAST:event_SalesReportPanelMouseExited

    private void textHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textHomeMouseClicked
        // TODO add your handling code here:
        DashboardNew home = new DashboardNew();
                    home.setVisible(true);
    }//GEN-LAST:event_textHomeMouseClicked

    private void MenuLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLabel1MouseClicked
        // TODO add your handling code here:
//        MenuLabel1 menu = new MenuLabel1();
//        dash.setLayout(new BorderLayout());
//        dash.removeAll();
//        dash.add(menu,BorderLayout.CENTER);
//        dash.revalidate();
//        dash.repaint();
    }//GEN-LAST:event_MenuLabel1MouseClicked

    private void COLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COLDActionPerformed

    private void LogoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbtnMouseClicked
        // TODO add your handling code here:
        LoginForm obj = new LoginForm();
            obj.setVisible(true);
    }//GEN-LAST:event_LogoutbtnMouseClicked

    private void orderViewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderViewPanelMouseClicked
        // TODO add your handling code here:
        
        OrderView odv = new OrderView();
         dash.setLayout(new BorderLayout());
                dash.removeAll();
                dash.add(odv, BorderLayout.CENTER);
                dash.revalidate();
                dash.repaint();
        
    }//GEN-LAST:event_orderViewPanelMouseClicked

    private void orderViewPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderViewPanelMouseEntered
        // TODO add your handling code here:
        orderViewPanel.setBackground(new Color(0,120,120));
        orderViewPanel.setForeground(Color.white);
    }//GEN-LAST:event_orderViewPanelMouseEntered

    private void orderViewPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderViewPanelMouseExited
        // TODO add your handling code here:
        orderViewPanel.setBackground(new Color(0,140,140));
        orderViewPanel.setForeground(new Color(255,236,209));
    }//GEN-LAST:event_orderViewPanelMouseExited

    private void OrderViewLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderViewLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderViewLabelMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardNew().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> COLD;
    private javax.swing.JLabel ColdL;
    private javax.swing.JComboBox<String> Common;
    private javax.swing.JLabel CommonL;
    private javax.swing.JLabel CustomerLabel;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JPanel FullPanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JComboBox<String> Hot;
    private javax.swing.JLabel HotL;
    private javax.swing.JComboBox<String> Iced;
    private javax.swing.JLabel IcedL;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JLabel MenuLabel1;
    private javax.swing.JPanel MenuitemPanel;
    private javax.swing.JPanel MenuitemPanel1;
    private javax.swing.JLabel OrderViewLabel;
    private javax.swing.JLabel OrederedLabel;
    private javax.swing.JPanel OrederedPanel;
    private javax.swing.JLabel SalesReportLabel;
    private javax.swing.JPanel SalesReportPanel;
    private javax.swing.JLabel StaffLabel;
    private javax.swing.JPanel StaffMangerPanel;
    private javax.swing.JPanel dash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel orderViewPanel;
    private javax.swing.JLabel textHome;
    // End of variables declaration//GEN-END:variables
}
