package com.rajat.cafenewproject;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author i_rajat_1
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        super("Login");
        initComponents();
    }
    
      Singleton instanceobj = Singleton.Display();
      
      void getValidation(){
  
                    if(useremail.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Enter your Email !");
                    }else if(!useremail.getText().endsWith("@gmail.com")){
                        JOptionPane.showMessageDialog(this, "Gmail end with @gmail.com");
                    }   else if(Password.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Enter your Password !");
                    }   else if(Password.getText().length()  < 6 )    {  
                        JOptionPane.showMessageDialog(this, "Enter your Password greater than 6 digit !");
                    }       else {
                        
                        if(useremail.getText().equals("Admin@gmail.com") && Password.getText().equals("123456")){
                        DashboardNew screen = new DashboardNew();
                        screen.setVisible(true);
                        dispose();
                        }else{
                            JOptionPane.showMessageDialog(this,"Enter Valid Details !");
                        }
//                        try {
//                        String isntVar = "INSERT INTO registered(email,password) values(?,?)";
//                        PreparedStatement prestobj = instanceobj.conn.prepareCall(isntVar);
//                        
//                        
////                        PreparedStatement ps = Singleton.conn.prepareCall(isntVar);
//                        
////                            ps.setString(1, username.getText());
//                            prestobj.setString(1, useremail.getText());
////                            ps.setString(3, userContact.getText());
//                            prestobj.setString(2, password.getText());
//                            
//                            
//                                          if(prestobj.executeUpdate() > 0){                                       
//                                         JOptionPane.showMessageDialog(this,"Data Inserted !");   
//                                            Dashboard dobj = new Dashboard();
//                                                   dobj.setVisible(true);
//                            System.out.println("Data Inserted !");
//                        }
//                    }   catch(SQLException e)    {
//                            System.out.println(e);
//                    }
                    }   
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlloginform = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        useremail = new javax.swing.JTextField();
        PasswordLabek = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        Show = new javax.swing.JCheckBox();
        Cancelbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 252, 209));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 250, 245));
        jPanel1.setForeground(new java.awt.Color(255, 246, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlloginform.setBackground(new java.awt.Color(255, 255, 255));
        jlloginform.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlloginform.setForeground(new java.awt.Color(230, 188, 105));
        jlloginform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlloginform.setText("Admin Login");
        jPanel1.add(jlloginform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 430, 40));

        EmailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(230, 188, 105));
        EmailLabel.setText("Enter Email");
        jPanel1.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, 20));

        useremail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useremailActionPerformed(evt);
            }
        });
        jPanel1.add(useremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 160, -1));

        PasswordLabek.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordLabek.setForeground(new java.awt.Color(230, 188, 105));
        PasswordLabek.setText("Password");
        PasswordLabek.setMaximumSize(new java.awt.Dimension(62, 16));
        PasswordLabek.setMinimumSize(new java.awt.Dimension(62, 16));
        PasswordLabek.setPreferredSize(new java.awt.Dimension(62, 16));
        jPanel1.add(PasswordLabek, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 110, 20));

        btnsubmit.setBackground(new java.awt.Color(0, 57, 55));
        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(230, 188, 105));
        btnsubmit.setText("SUBMIT");
        btnsubmit.setMaximumSize(new java.awt.Dimension(88, 24));
        btnsubmit.setMinimumSize(new java.awt.Dimension(88, 24));
        btnsubmit.setPreferredSize(new java.awt.Dimension(88, 24));
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        btnsubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnsubmitKeyPressed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 130, 30));
        btnsubmit.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 160, -1));

        Show.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Show.setForeground(new java.awt.Color(255, 255, 255));
        Show.setText("Show Password");
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
        });
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        jPanel1.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 20));

        Cancelbtn.setBackground(new java.awt.Color(0, 57, 55));
        Cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cancelbtn.setForeground(new java.awt.Color(230, 188, 105));
        Cancelbtn.setText("CANCEL");
        Cancelbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelbtnMouseClicked(evt);
            }
        });
        jPanel1.add(Cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\i_rajat_1\\Pictures\\DownloadPics\\mars1.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
                    // TODO add your handling code here:
                  getValidation();
                    
                    
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnsubmitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsubmitKeyPressed
                    // TODO add your handling code here:                  
                    getValidation();
    }//GEN-LAST:event_btnsubmitKeyPressed

    private void useremailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useremailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useremailActionPerformed

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_ShowMouseClicked

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        // TODO add your handling code here:
        if(Show.isSelected()){
            Password.setEchoChar((char)(0));
        }else{
            Password.setEchoChar(('*'));
        }
    }//GEN-LAST:event_ShowActionPerformed

    private void CancelbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelbtnMouseClicked
        // TODO add your handling code here:
                this.dispose();
    }//GEN-LAST:event_CancelbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordLabek;
    private javax.swing.JCheckBox Show;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlloginform;
    private javax.swing.JTextField useremail;
    // End of variables declaration//GEN-END:variables
}
