/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.rajat.cafenewproject;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author i_rajat_1
 */
public class Menuitem extends javax.swing.JPanel {
    
    
    
Singleton con = Singleton.Display();
ArrayList<MenuModel> Menulist = new ArrayList<>();
  
    public Menuitem() {
        initComponents();
        getTable();
    }
    
    void getTable(){
        try{
            String MenuHeader[] = {"id","Coffee","CoffeeType","Price","Category"};
            DefaultTableModel Model = new DefaultTableModel(null,MenuHeader);
            MenuTable.setModel(Model);
            Model.setRowCount(0);
            
            String getQuerry = "SELECT * FROM Menutable ";
            Statement obj = con.conn.createStatement();
            ResultSet resultobj = obj.executeQuery(getQuerry);
             Menulist.clear();
             
             while(resultobj.next()){
             Menulist.add(new MenuModel(
                     resultobj.getInt("id"),
                     resultobj.getString("Coffee"),
                     resultobj.getString("CoffeeType"),
                     resultobj.getString("Price"),
                     resultobj.getString("Category")
             ));             
             }
             
             Object[] row = new Object[5];
             
             for(MenuModel itemVar : Menulist){
                 row[0] = itemVar.getid();
                 row[1] = itemVar.getCoffee();
                 row[2] = itemVar.getCoffeeType();      // CoffeeTypes
                 row[3] = itemVar.getPrice();
                 row[4] = itemVar.getCategory();
                 Model.addRow(row);
             }   
             
        }catch(SQLException exception){
           System.out.println("Check Excepiton: "+exception);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        MenuLabel = new javax.swing.JLabel();
        AddMenuLabel = new javax.swing.JLabel();
        CoffeesPanel = new javax.swing.JPanel();
        CoffeeLabel = new javax.swing.JLabel();
        CoffeeTypesPanel = new javax.swing.JPanel();
        CoffeeTypeLabel = new javax.swing.JLabel();
        Addbtn = new javax.swing.JButton();
        CoffeeType = new javax.swing.JComboBox<>();
        CoffeeQuantityPanel = new javax.swing.JPanel();
        PriceLabel = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        Coffee = new javax.swing.JComboBox<>();
        CategoryPanel = new javax.swing.JPanel();
        CategoryLabel = new javax.swing.JLabel();
        Category = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        MenuTable = new javax.swing.JTable();
        Backbtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(630, 520));
        setPreferredSize(new java.awt.Dimension(630, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPanel.setBackground(new java.awt.Color(0, 140, 140));
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MenuLabel.setForeground(new java.awt.Color(255, 236, 209));
        MenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuLabel.setText("MENU ITEMS");
        MenuPanel.add(MenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 630, 20));

        add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        AddMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddMenuLabel.setText("Add Menu");
        add(AddMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 630, 30));

        CoffeesPanel.setBackground(new java.awt.Color(255, 255, 255));
        CoffeesPanel.setMinimumSize(new java.awt.Dimension(160, 38));
        CoffeesPanel.setPreferredSize(new java.awt.Dimension(160, 38));
        CoffeesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoffeeLabel.setBackground(new java.awt.Color(51, 0, 0));
        CoffeeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CoffeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CoffeeLabel.setText("Coffee");
        CoffeeLabel.setMaximumSize(new java.awt.Dimension(41, 17));
        CoffeeLabel.setMinimumSize(new java.awt.Dimension(41, 17));
        CoffeeLabel.setPreferredSize(new java.awt.Dimension(41, 17));
        CoffeesPanel.add(CoffeeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        add(CoffeesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 130, 30));

        CoffeeTypesPanel.setBackground(new java.awt.Color(255, 255, 255));
        CoffeeTypesPanel.setForeground(new java.awt.Color(102, 0, 0));

        CoffeeTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CoffeeTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CoffeeTypeLabel.setText("Types");

        javax.swing.GroupLayout CoffeeTypesPanelLayout = new javax.swing.GroupLayout(CoffeeTypesPanel);
        CoffeeTypesPanel.setLayout(CoffeeTypesPanelLayout);
        CoffeeTypesPanelLayout.setHorizontalGroup(
            CoffeeTypesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoffeeTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        CoffeeTypesPanelLayout.setVerticalGroup(
            CoffeeTypesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoffeeTypesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoffeeTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        add(CoffeeTypesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 120, 30));

        Addbtn.setBackground(new java.awt.Color(0, 140, 140));
        Addbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addbtn.setForeground(new java.awt.Color(255, 236, 209));
        Addbtn.setText("ADD");
        Addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddbtnMouseClicked(evt);
            }
        });
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 170, -1));

        CoffeeType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CoffeeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));
        CoffeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffeeTypeActionPerformed(evt);
            }
        });
        add(CoffeeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 120, -1));

        CoffeeQuantityPanel.setBackground(new java.awt.Color(255, 255, 255));

        PriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceLabel.setText("Price");

        javax.swing.GroupLayout CoffeeQuantityPanelLayout = new javax.swing.GroupLayout(CoffeeQuantityPanel);
        CoffeeQuantityPanel.setLayout(CoffeeQuantityPanelLayout);
        CoffeeQuantityPanelLayout.setHorizontalGroup(
            CoffeeQuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        CoffeeQuantityPanelLayout.setVerticalGroup(
            CoffeeQuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoffeeQuantityPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PriceLabel)
                .addContainerGap())
        );

        add(CoffeeQuantityPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 120, 30));

        Price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 120, -1));

        Coffee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Coffee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espresso", "Cappuccino", "Latte", "Macchiato", "Irish Coffee", "Americano", "Clod Brew", "Frapped", "Affogato", "Iced Vanilla", "Iced Flat White", "Iced Latte" }));
        add(Coffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, -1));

        CategoryPanel.setBackground(new java.awt.Color(255, 255, 255));
        CategoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CategoryLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CategoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CategoryLabel.setText("Category");
        CategoryPanel.add(CategoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 120, -1));

        add(CategoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 120, 30));

        Category.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Common", "Hot", "Cold", "Iced" }));
        add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 120, -1));

        MenuTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MenuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Coffee", "Types", "Quantity", "Category"
            }
        ));
        jScrollPane1.setViewportView(MenuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 590, 190));

        Backbtn.setBackground(new java.awt.Color(0, 140, 140));
        Backbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 236, 209));
        Backbtn.setText("BACK");
        Backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackbtnMouseClicked(evt);
            }
        });
        add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, -1));

        Deletebtn.setBackground(new java.awt.Color(0, 140, 140));
        Deletebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deletebtn.setForeground(new java.awt.Color(255, 236, 209));
        Deletebtn.setText("DELETE");
        add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 170, -1));

        Updatebtn.setBackground(new java.awt.Color(0, 140, 140));
        Updatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Updatebtn.setForeground(new java.awt.Color(255, 236, 209));
        Updatebtn.setText("UPDATE");
        add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CoffeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffeeTypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CoffeeTypeActionPerformed

    private void AddbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbtnMouseClicked
        // TODO add your handling code here:
        if(Addbtn.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter your Coffee !");
                }  else if (Price.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Enter Coffee Price !");
                } else {
                       try {
                           
    String isntVar = " INSERT INTO MenuTable(Coffee,CoffeeType,Price,Category) values(?,?,?,?)";
                                   PreparedStatement ps = con.conn.prepareCall(isntVar);
                                   ps.setString(1,Coffee.getSelectedItem().toString());
                                   ps.setString(2,CoffeeType.getSelectedItem().toString());
                                   ps.setDouble(3,Double.parseDouble(Price.getText()));                                 
                                   ps.setString(4,Category.getSelectedItem().toString());
                                   
                                   if(ps.executeUpdate() >  0){
                     JOptionPane.showMessageDialog(this, "Data Inserted !");                    
                 }
                     }catch(SQLException e){
                         System.out.println("Check Exception: "+e);
                     }
                }                    
    }//GEN-LAST:event_AddbtnMouseClicked

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
//        String Comboboxname = CoffeeCombobox.getSelectedItem().toString();       
        
    }//GEN-LAST:event_AddbtnActionPerformed

    private void BackbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbtnMouseClicked
        // TODO add your handling code here:
        DashboardNew dash = new DashboardNew();
        dash.setVisible(true);
    }//GEN-LAST:event_BackbtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddMenuLabel;
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Backbtn;
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JPanel CategoryPanel;
    private javax.swing.JComboBox<String> Coffee;
    private javax.swing.JLabel CoffeeLabel;
    private javax.swing.JPanel CoffeeQuantityPanel;
    private javax.swing.JComboBox<String> CoffeeType;
    private javax.swing.JLabel CoffeeTypeLabel;
    private javax.swing.JPanel CoffeeTypesPanel;
    private javax.swing.JPanel CoffeesPanel;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JTable MenuTable;
    private javax.swing.JTextField Price;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
