/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.rajat.cafenewproject;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class OrderView extends javax.swing.JPanel {
    Singleton conn = Singleton.Display();

    /**
     * Creates new form OrderView
     */
    public OrderView() {
        initComponents();
        getOrderView();
    }
    void getOrderView() {
        
    String header[] = {"Id", "CustomerName", "Coffee Name", "Type", "Qunatity", "Category", "Price", "Total Price"};

    DefaultTableModel model = new DefaultTableModel(null, header);
    billViewTable.setModel(model);
    model.setRowCount(0);

    String order = "SELECT id, customerName FROM orderedtable";
    try {
        PreparedStatement ps1 = conn.conn.prepareStatement(order);
        ResultSet rs1 = ps1.executeQuery();
        while (rs1.next()) {
            int orderId = rs1.getInt("id");
            String customerName = rs1.getString("customerName");

            // Now fetch only related orderDetails
            String query2 = "SELECT id, orderId, coffeeName, type, quantity, category, price FROM orderDetailsTable WHERE orderId = ?";
            PreparedStatement ps2 = conn.conn.prepareStatement(query2);
            ps2.setInt(1, orderId); // ✅ Set specific orderId
            ResultSet result = ps2.executeQuery();

            while (result.next()) {
                int orderDetailsId = result.getInt("id");
                String coffeeName = result.getString("coffeeName");
                String category = result.getString("category");
                String type = result.getString("type");
                int quantity = result.getInt("quantity");
                double price = result.getDouble("price");

                double productTotal = quantity * price;

                Object[] row = {orderDetailsId, customerName, coffeeName, type, quantity, category, price, productTotal};
                model.addRow(row);
            }
        }
    } catch (SQLException ex) {
        System.getLogger(OrderView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billViewTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        billViewTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        billViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        billViewTable.setRowHeight(30);
        billViewTable.setShowHorizontalLines(true);
        billViewTable.getTableHeader().setReorderingAllowed(false);
        billViewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billViewTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billViewTableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billViewTableMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(billViewTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 620, 480));

        jPanel2.setBackground(new java.awt.Color(0, 140, 140));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 236, 209));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order View");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void billViewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billViewTableMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_billViewTableMouseClicked

    private void billViewTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billViewTableMouseEntered
        // TODO add your handling code here:
    
        billViewTable.setSelectionBackground(new Color(102,0,0));
        billViewTable.setSelectionForeground(Color.white);
    }//GEN-LAST:event_billViewTableMouseEntered

    private void billViewTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billViewTableMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_billViewTableMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billViewTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
