/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.rajat.cafenewproject;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author i_rajat_1
 */
public class Staff extends javax.swing.JPanel {

    /**
     * Creates new form Staff
     */
    
    Singleton con = Singleton.Display();
    int selectedId = 0;
   ArrayList<StaffModel> Stafflist = new ArrayList<>();
    
    public Staff() {
        initComponents();
        getTable();
    }

    void getTable(){
        try{
            String StaffHeader[] = {"id","Name","Work","Contact","Address"};
            DefaultTableModel Model = new DefaultTableModel(null,StaffHeader);
            StaffTable.setModel(Model);
            Model.setRowCount(0);
            
            String getQuerry = "SELECT * FROM StaffTable ";
            Statement obj = con.conn.createStatement();
            ResultSet resultobj = obj.executeQuery(getQuerry);
             Stafflist.clear();
             
             while(resultobj.next()){
             Stafflist.add(new StaffModel(
                     resultobj.getInt("id"),
                     resultobj.getString("Name"),
                     resultobj.getString("Work"),
                     resultobj.getString("Contact"),
                     resultobj.getString("Address")
             ));
////             
             }
             
             Object[] row = new Object[5];
             
             for(StaffModel itemVar : Stafflist){
                 row[0] = itemVar.getid();
                 row[1] = itemVar.getName();
                 row[2] = itemVar.getWork();      // CoffeeTypes
                 row[3] = itemVar.getContact();
                 row[4] = itemVar.getAddress();
                 Model.addRow(row);
             }   
             
        }catch(SQLException exception){
           System.out.println("Check Excepiton: "+exception);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffPanel = new javax.swing.JPanel();
        StaffLabel = new javax.swing.JLabel();
        VarPanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        ContactLabel = new javax.swing.JLabel();
        Contact = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        WorkLabel = new javax.swing.JLabel();
        Work = new javax.swing.JComboBox<>();
        Submitbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StaffTable = new javax.swing.JTable();
        Deletebtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Resetbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(630, 530));
        setPreferredSize(new java.awt.Dimension(630, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffPanel.setBackground(new java.awt.Color(0, 140, 140));
        StaffPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        StaffLabel.setForeground(new java.awt.Color(255, 236, 209));
        StaffLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StaffLabel.setText("Staff Details ");
        StaffPanel.add(StaffLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 630, 30));

        add(StaffPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        VarPanel.setForeground(new java.awt.Color(102, 0, 0));
        VarPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NameLabel.setText("Full Name");
        VarPanel.add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, -1));

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        VarPanel.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, -1));

        ContactLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ContactLabel.setText("Contact");
        VarPanel.add(ContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 180, -1));

        Contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VarPanel.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 180, -1));

        AddressLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddressLabel.setText("Address");
        VarPanel.add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 180, -1));

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VarPanel.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 180, -1));

        WorkLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WorkLabel.setText("Work");
        VarPanel.add(WorkLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 180, -1));

        Work.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Work.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manger", "Chef", "Waiter" }));
        VarPanel.add(Work, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, -1));

        Submitbtn.setBackground(new java.awt.Color(0, 140, 140));
        Submitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submitbtn.setForeground(new java.awt.Color(255, 236, 209));
        Submitbtn.setText("SUBMIT");
        Submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbtnActionPerformed(evt);
            }
        });
        VarPanel.add(Submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 140, -1));

        StaffTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StaffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Work", "Contact", "Address"
            }
        ));
        jScrollPane1.setViewportView(StaffTable);

        VarPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 550, 160));

        Deletebtn.setBackground(new java.awt.Color(0, 140, 140));
        Deletebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deletebtn.setForeground(new java.awt.Color(255, 236, 209));
        Deletebtn.setText("DELETE");
        Deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletebtnMouseClicked(evt);
            }
        });
        VarPanel.add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 190, -1));

        Updatebtn.setBackground(new java.awt.Color(0, 140, 140));
        Updatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Updatebtn.setForeground(new java.awt.Color(255, 236, 209));
        Updatebtn.setText("UPDATE");
        VarPanel.add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 190, -1));

        Resetbtn.setBackground(new java.awt.Color(0, 140, 140));
        Resetbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Resetbtn.setForeground(new java.awt.Color(255, 236, 209));
        Resetbtn.setText("RESET");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbtnActionPerformed(evt);
            }
        });
        VarPanel.add(Resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, -1));

        Backbtn.setBackground(new java.awt.Color(0, 140, 140));
        Backbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 236, 209));
        Backbtn.setText("BACK");
        Backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackbtnMouseClicked(evt);
            }
        });
        VarPanel.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 160, -1));

        add(VarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void BackbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbtnMouseClicked
        // TODO add your handling code here:
        DashboardNew dash = new DashboardNew();
        dash.setVisible(true);
    }//GEN-LAST:event_BackbtnMouseClicked

    private void DeletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebtnMouseClicked
        // TODO add your handling code here:
        if (selectedId <= 0) {
        JOptionPane.showMessageDialog(this, "No record selected to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        String deleteQuery = "DELETE FROM customertable WHERE id=?";
        try {
            PreparedStatement ps = con.conn.prepareStatement(deleteQuery);
            ps.setInt(1, selectedId);
            int deleted = ps.executeUpdate();

            if (deleted > 0) {
                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
                selectedId = 0;
//                StaffTable();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete record.");
            }
        } catch (SQLException e) {
            System.out.println("Delete error: " + e);
        }
    }
    }//GEN-LAST:event_DeletebtnMouseClicked

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed
        // TODO add your handling code here
                
                if(Name.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Enter your Name !");
                }   else if(Contact.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Enter your Phone Number !");
                }  else if(Contact.getText().length() < 10){
                    JOptionPane.showMessageDialog(this, "Your Number is less-than 10-digits \n Please entery 10-digits Number !");
                }else if(Contact.getText().length() > 10){
                    JOptionPane.showMessageDialog(this, "Your Number is Greater-than 10-digits \n Please entery 10-digits Number !");
                }else if(Address.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Enter your Address !");
                }   else {
                           try {
                           
    String isntVar = " INSERT INTO StaffTable(Name,Work,Contact,Address) values(?,?,?,?)";
                                   PreparedStatement ps = con.conn.prepareCall(isntVar);
                                   ps.setString(1,Name.getText());
                                   ps.setString(2,Work.getSelectedItem().toString());
                                   ps.setString(3,Contact.getText());                                 
                                   ps.setString(4,Address.getText());
                                   
                                   if(ps.executeUpdate() >  0){
                     JOptionPane.showMessageDialog(this, "Data Inserted !");                    
                 }
                     }catch(SQLException e){
                         System.out.println("Check Exception: "+e);
                     }
                } 

        
    }//GEN-LAST:event_SubmitbtnActionPerformed

    private void ResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbtnActionPerformed
        // TODO add your handling code here:
        Name.setText("");
        Contact.setText("");
        Address.setText("");
    }//GEN-LAST:event_ResetbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField Contact;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JLabel StaffLabel;
    private javax.swing.JPanel StaffPanel;
    private javax.swing.JTable StaffTable;
    private javax.swing.JButton Submitbtn;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JPanel VarPanel;
    private javax.swing.JComboBox<String> Work;
    private javax.swing.JLabel WorkLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
